<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>TAuto.Core</RootNamespace>
    <AssemblyName>TAuto.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NCrontab" Version="3.4.0" />
  </ItemGroup>

</Project>