<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows$(WindowsTfmVersion)</TargetFramework>
    <TargetPlatformVersion>$(WindowsTfmVersion)</TargetPlatformVersion>
    <TargetPlatformMinVersion>$(WindowsTfmVersion)</TargetPlatformMinVersion>
    <TargetPlatformMoniker>Windows,Version=$(TargetPlatformVersion)</TargetPlatformMoniker>
    <TargetPlatformDisplayName>Windows SDK</TargetPlatformDisplayName>
    <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>TAuto.Automation</RootNamespace>
        <AssemblyName>TAuto.Automation</AssemblyName>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TAuto.Core\TAuto.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
      <PackageReference Include="Obfuscar" Version="2.2.50">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
    </ItemGroup>

</Project>
